# keybinding:
#   commits:
#     moveDownCommit: j
#     moveUpCommit: k
#   universal:
#     nextBlock: <c-j>
#     prevBlock: <c-k>
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers
  allBranchesLogCmd: git log --graph --color=always --date=format:'%Y-%m-%d %H:%M:%S'
  branchLogCmd: git log --graph --color=always --date=format:'%Y-%m-%d %H:%M:%S'
gui:
  language: "en"
  nerdFontsVersion: "3"
os:
  editPreset: "nvim-remote"

